pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'jdk8' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'mvn jar:jar install:install help:evaluate -Dexpression=project.name'
             }
        }
      }
    post {
          always {
                    archiveArtifacts artifacts: '**/*-0.0.1-SNAPSHOT.jar', fingerprint: true
                 }
           }
 }
