openapi: 3.0.0
info:
  title: Config server
  description: web service for configuration settings to configured clients
  version: 0.0.1
servers:
  - url: 'http://localhost:1999'
    description: Local computer -/stwitter-service/master