openapi: 3.0.0
info:
  title: Tasker Service Project
  description:
    Tasker is a simple task tracking web service.
  version: 0.0.1
servers:
  - url: 'http://localhost:7979'
    description: Local computer
paths:
  /tasks:
    post:
      summary: Create a new task with the given information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskViewModel'
      responses:
        '201':
          description: new task with advertisement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskViewModel'
        '400':
          description: Invalid request syntax.
        '422':
          description: Incomplete Task information. Some required fields missing.
    get:
      summary: Retrieves a list of all tasks.
      responses:
        '200':
          description: A list of all Tasks and adverstisement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskViewModel'

  /tasks/{taskId}:
    get:
      summary: Retrieves the task with the given task id.
      parameters:
        - name: taskId
          in: path
          required: true
          description: Id of the task you would like to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: task and advertisement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskViewModel'

    put:
      summary: Updates the entry for the task with the given task id.
      parameters:
        - name: taskId
          in: path
          required: true
          description: Id of the task you would like to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskViewModel'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskViewModel'
        '400':
          description: Invalid request syntax.
        '422':
          description: Incomplete task information. Some required fields missing.

    delete:
      summary: Deletes the entry for the task with the given task id.
      parameters:
        - name: taskId
          in: path
          required: true
          description: Id of the task you would like to delete.
          schema:
            type: integer
      responses:
        '204':
          description: No content.

  /tasks/category/{category}:
    get:
      summary: Retrieves the task with the given category.
      parameters:
        - name: category
          in: path
          required: true
          description: category of the task you would like to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: A list of all Tasks and adverstisement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskViewModel'



components:
  schemas:
    TaskViewModel:
      properties:
        id:
          type: integer
        description:
          type: string
          minLength: 1
          maxLength: 255
        createDate:
          type: string
          pattern: 'yyyy-mm-dd'
        dueDate:
          type: string
          pattern: 'yyyy-mm-dd'
        category:
          type: string
          maxLength: 50
        advertisement:
          type: string
      required:
        - id
        - description
        - createDate
        - dueDate



